version: "3.8"

services:
  db:
    container_name: pet-database
    image: mysql:latest
    volumes:
      - ./db/data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet-backend
    environment:
      DB_HOST: pet-database
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]
