openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
  description: Test 관리 API 문서

paths:
  /api/v1/tests:
    get:
      summary: 전체 Test 리스트 조회
      tags:
        - Tests
      security:
        - bearerAuth: []
      description: 모든 Test 리스트를 조회합니다.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: 페이지 번호
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: 페이지당 항목 수
      responses:
        '200':
          description: 전체 Test 리스트 조회가 성공적으로 완료되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 전체 검사 리스트 조회가 성공되었습니다.
                  data:
                    type: object
                    properties:
                      totalItems:
                        type: integer
                        example: 100
                        description: 전체 항목 수
                      totalPages:
                        type: integer
                        example: 10
                        description: 전체 페이지 수
                      currentPage:
                        type: integer
                        example: 1
                        description: 현재 페이지
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Test'
        '500':
          description: 서버 오류로 인해 전체 Test 리스트 조회에 실패했습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 전체 검사 리스트 조회에 실패했습니다.

  /api/v1/tests/{testId}:
    get:
      summary: 특정 Test 정보 조회
      tags:
        - Tests
      security:
        - bearerAuth: []
      description: ID를 사용하여 특정 Test 정보를 조회합니다.
      parameters:
        - in: path
          name: testId
          schema:
            type: integer
          required: true
          description: 조회할 Test ID
      responses:
        '200':
          description: 특정 Test 정보 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 검사 정보 조회 성공
                  data:
                    $ref: '#/components/schemas/Test'
        '404':
          description: Test 정보를 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 검사 정보를 찾을 수 없습니다.
        '500':
          description: 서버 오류로 인해 검사 정보 조회 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 검사 정보 조회에 실패했습니다.
    put:
      summary: Test 상태 업데이트
      tags:
        - Tests
      description: testId를 사용하여 Test 상태를 '코멘트 대기'로 업데이트합니다.
      parameters:
        - in: path
          name: testId
          schema:
            type: integer
          required: true
          description: 상태 업데이트할 Test ID
      responses:
        '200':
          description: 상태 업데이트 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 상태가 코멘트 대기로 변경되었습니다.
        '400':
          description: 잘못된 요청 (testId가 필요)
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: testId가 필요합니다.
        '404':
          description: 해당 testId를 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 해당 testId를 찾을 수 없습니다.
        '500':
          description: 서버 오류로 인해 상태 업데이트 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 상태 업데이트에 실패했습니다.
  
    delete:
      summary: 특정 Test 정보 삭제
      tags:
        - Tests
      security:
        - bearerAuth: []
      description: ID를 사용하여 특정 Test 정보를 삭제합니다.
      parameters:
        - in: path
          name: testId
          schema:
            type: integer
          required: true
          description: 삭제할 Test ID
      responses:
        '200':
          description: 특정 Test 정보 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 검사 정보가 삭제되었습니다.
        '400':
          description: 삭제할 Test 정보를 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 검사 정보 삭제에 실패하였습니다.
        '500':
          description: 서버 오류로 인해 검사 정보 삭제 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 검사 정보 삭제에 실패했습니다.

  /api/v1/tests/comment:
    post:
      summary: Test에 코멘트 추가
      tags:
        - Tests
      description: 특정 Test에 코멘트를 추가합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                test_id:
                  type: integer
                  description: Test ID
                comment:
                  type: string
                  description: 추가할 코멘트
              required:
                - test_id
                - comment
      responses:
        '200':
          description: 코멘트 추가 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 코멘트 추가 성공했습니다.
        '400':
          description: 잘못된 요청 (test_id와 comment가 필요)
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: test_id와 comment는 필수 항목입니다.
        '500':
          description: 서버 오류로 인해 코멘트 추가 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 코멘트 추가에 실패했습니다.

  /api/v1/tests/push:
    post:
      summary: FCM 푸시 알림 전송
      tags:
        - Notifications
      description: FCM을 통해 푸시 알림을 전송합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                test_id:
                  type: integer
                  description: test_id
                token:
                  type: string
                  description: FCM 토큰
              required:
                - token
      responses:
        '200':
          description: 성공적으로 푸시 알림이 전송되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          description: 잘못된 요청 (유효하지 않은 FCM 토큰 등)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: The registration token is not a valid FCM registration token

  /api/v1/tests/search:
    get:
      summary: 사용자 전화번호와 펫 이름으로 Test 조회
      tags:
        - Tests
      security:
        - bearerAuth: []
      description: 사용자 전화번호와 펫 이름을 사용하여 Test를 조회합니다.
      parameters:
        - in: query
          name: petName
          schema:
            type: string
          required: true
          description: 조회할 펫 이름
      responses:
        '200':
          description: 테스트 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  tests:
                    type: array
                    items:
                      $ref: '#/components/schemas/Test'
        '400':
          description: 잘못된 요청 (펫 이름이 필요)
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 펫 이름이 필요합니다.
        '404':
          description: 해당 조건의 펫을 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 해당 조건의 펫을 찾을 수 없습니다.
        '500':
          description: 서버 오류로 인해 테스트 조회 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 펫 정보 조회에 실패했습니다.

  
components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: integer
          description: Test ID
        comment:
          type: string
          description: 코멘트
        hospital:
          type: string
          description: 병원명
        receivedAt:
          type: string
          format: date-time
          description: 접수 날짜
        resultDate:
          type: string
          format: date-time
          description: 결과 날짜
        guardianName:
          type: string
          description: 보호자 이름
        contactNumber:
          type: string
          description: 연락처
        petName:
          type: string
          description: 반려동물 이름
        species:
          type: string
          description: 종
        breed:
          type: string
          description: 품종
        age:
          type: integer
          description: 나이
        gender:
          type: string
          description: 성별
        weight:
          type: number
          format: float
          description: 체중
        hereditaryDisease:
          type: string
          description: 유전병
        feedingMethod:
          type: string
          description: 급여 방법
        supplements:
          type: string
          description: 보충제
        medication:
          type: string
          description: 약물
        status:
          type: string
          enum:
            - 코멘트 요청
            - 코멘트 대기
            - 코멘트 완료
          description: 현재 상태
        createdAt:
          type: string
          format: date-time
          description: 생성 날짜
        updatedAt:
          type: string
          format: date-time
          description: 수정 날짜
        isDeleted:
          type: boolean
          description: 삭제 여부