openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
  description: Test 관리 API 문서

paths:
  /api/v1/tests:
    post:
      summary: Test 생성
      tags:
        - Tests
      description: 새로운 Test를 생성합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: 성공적으로 Test가 생성되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Test 생성에 성공했습니다.
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: Test ID
        '400':
          description: 잘못된 요청.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
        '500':
          description: 서버 오류로 인해 Test 생성에 실패했습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: Test 생성에 실패했습니다.
  /api/v1/tests/comment:
    post:
      summary: Test에 코멘트 추가
      tags:
        - Tests
      description: 특정 Test에 코멘트를 추가합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                test_id:
                  type: integer
                  description: Test ID
                comment:
                  type: string
                  description: 추가할 코멘트
              required:
                - test_id
                - comment
      responses:
        '200':
          description: 코멘트 추가 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 코멘트 추가 성공했습니다.
        '400':
          description: 잘못된 요청 (test_id와 comment가 필요)
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: test_id와 comment는 필수 항목입니다.
        '500':
          description: 서버 오류로 인해 코멘트 추가 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: 코멘트 추가에 실패했습니다.

  /api/v1/tests/push:
    post:
      summary: FCM 푸시 알림 전송
      tags:
        - Notifications
      description: FCM을 통해 푸시 알림을 전송합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: FCM 토큰
              required:
                - token
      responses:
        '200':
          description: 성공적으로 푸시 알림이 전송되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          description: 잘못된 요청 (유효하지 않은 FCM 토큰 등)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: The registration token is not a valid FCM registration token

components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: integer
          description: Test ID