openapi: 3.0.0
info:
  title: 펫 등록 API
  version: 1.0.0
  description: 펫 등록을 위한 API
servers:
  - url: http://localhost:3000
paths:
  /api/v1/pets:
    post:
      summary: 새로운 펫 등록(로그인 필요)
      tags:
        - Pets
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: 펫 이미지 파일
                name:
                  type: string
                  description: 펫 이름
                age:
                  type: integer
                  description: 펫 나이
                gender:
                  type: string
                  description: 펫 성별
                species:
                  type: string
                  description: 펫 종
                weight:
                  type: number
                  description: 펫 무게
                feed:
                  type: string
                  description: 펫 먹이 정보
      responses:
        200:
          description: 펫 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  message:
                    type: string
        400:
          description: 필수 필드 누락
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  message:
                    type: string
        500:
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  message:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT